Repository jupyterlab/hatch-jupyter-builder, pull requests merged in 2022-06, with the labels that each got.

#20 Fix handling of skip-if-exists
  README.md
  hatch_jupyter_builder/plugin.py
Labels: bug

#23 Chore: fix metadata for Source in pyproject.toml
  pyproject.toml
Labels: maintenance

#21 Add migration and compare script
  .github/workflows/tests.yml
  README.md
  hatch_jupyter_builder/migration/__main__.py
  hatch_jupyter_builder/migration/_migrate.py
  hatch_jupyter_builder/migration/compare.py
  hatch_jupyter_builder/utils.py
  pyproject.toml
  tests/conftest.py
  tests/data/myextension/.eslintignore
  tests/data/myextension/.eslintrc.js
  tests/data/myextension/.github/workflows/build.yml
  tests/data/myextension/.github/workflows/check-release.yml
  tests/data/myextension/.gitignore
  tests/data/myextension/.prettierignore
  tests/data/myextension/.prettierrc
  tests/data/myextension/.stylelintrc
  tests/data/myextension/CHANGELOG.md
  tests/data/myextension/LICENSE
  tests/data/myextension/MANIFEST.in
  tests/data/myextension/README.md
  tests/data/myextension/RELEASE.md
  tests/data/myextension/install.json
  tests/data/myextension/myextension/__init__.py
  tests/data/myextension/myextension/_version.py
  tests/data/myextension/package.json
  tests/data/myextension/pyproject.toml
  tests/data/myextension/schema/plugin.json
  tests/data/myextension/setup.py
  tests/data/myextension/src/index.ts
  tests/data/myextension/style/base.css
  tests/data/myextension/style/index.css
  tests/data/myextension/style/index.js
  tests/data/myextension/tsconfig.json
  tests/data/pyproject.toml
  tests/test_migration.py
  tests/test_npm_builder.py
Labels: enhancement

#27 Add a setup.py shim in migration script
  hatch_jupyter_builder/migration/_migrate.py
  tests/data/pyproject.toml
Labels: enhancement

#30 Automated Changelog Entry for 0.5.0 on main
  CHANGELOG.md
Labels: documentation

#29 Migration cleanup
  hatch_jupyter_builder/migration/__main__.py
  hatch_jupyter_builder/migration/_migrate.py
  hatch_jupyter_builder/migration/compare.py
  hatch_jupyter_builder/utils.py
  tests/data/pyproject.toml
  tests/test_migration.py
  tests/test_npm_builder.py
Labels: maintenance

#32 Automated Changelog Entry for 0.5.1 on main
  CHANGELOG.md
Labels: documentation

#33 Preserve other build reqs
  hatch_jupyter_builder/migration/_migrate.py
  tests/data/pyproject.toml
Labels: bug

#34 Automated Changelog Entry for 0.5.2 on main
  CHANGELOG.md
Labels: documentation

#35 Fix compare script
  hatch_jupyter_builder/migration/_migrate.py
  hatch_jupyter_builder/migration/compare.py
  pyproject.toml
  tests/data/pyproject.toml
  tests/test_migration.py
Labels: bug

#36 Add jupyter_packaging conversion wrapper
  hatch_jupyter_builder/migration/__main__.py
  hatch_jupyter_builder/migration/_migrate.py
  hatch_jupyter_builder/migration/jupyter_packaging.py
  tests/data/pyproject.toml
Labels: enhancement

#38 Rename migration scripts
  README.md
  hatch_jupyter_builder/compare_migrated/__init__.py
  hatch_jupyter_builder/compare_migrated/__main__.py
  hatch_jupyter_builder/migrate/__init__.py
  hatch_jupyter_builder/migrate/__main__.py
  hatch_jupyter_builder/migrate/_migrate.py
  hatch_jupyter_builder/migrate/jupyter_packaging.py
  pyproject.toml
  tests/test_migration.py
Labels: maintenance
