Repository jupyterlab/hatch-jupyter-builder, pull requests merged in 2022-08, with the labels that each got.

#52 Fix flake8 v5 compat
  .pre-commit-config.yaml
Labels: maintenance

#55 Fix command in `install_pre_commit_hook`
  hatch_jupyter_builder/utils.py
Labels: bug

#56 Automated Changelog Entry for 0.5.3 on main
  CHANGELOG.md
Labels: documentation

#49 Use version_template for package.json
  hatch_jupyter_builder/migrate/_migrate.py
  tests/data/npm_builder/pyproject.toml
Labels: bug

#58 More documentation cleanup
  README.md
  docs/source/background/index.rst
  docs/source/get_started/config.md
  docs/source/get_started/index.rst
  docs/source/reference/api_docs.rst
  docs/source/reference/changelog.md
  hatch_jupyter_builder/plugin.py
  hatch_jupyter_builder/utils.py
  pyproject.toml
Labels: documentation
